In [39]:
import pandas as pd
from sklearn.model_selection import train_test_split
from IPython.display import display
import numpy as np

%load_ext autoreload
%autoreload 2
import importlib
import sys
sys.path.append("../src/")
import modele
importlib.reload(modele)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


<module 'modele' from 'c:\\Users\\anton\\Downloads\\A3\\analyse données\\Winunmax\\notebooks\\../src\\modele.py'>

In [40]:
df = pd.read_csv("../data/preparee/dataframe_traite.csv")
#Je laisse game_id pour le moment pour des vérifications
X = df.drop(columns=["home_club_name","away_club_name","date","season","home_club_id","away_club_id","results"]) 
Y = df["results"]
display(X.head(3))
display(Y.head(3))

,game_id,home_club_position,away_club_position,difference classement,Difference value home et away,Ratio value home par away,LOG Ratio value home par away,winrate_home 1 ans,winrate_away 1 ans,difference winrate 1 ans,...,winrate_away 3 ans,difference winrate 3 ans,winrate_confrontation_home 1 ans,winrate_confrontation_home 3 ans,pos_moy_home_1_ans,pos_moy_away_1_ans,difference classement moyen 1 ans,pos_moy_home_3_ans,pos_moy_away_3_ans,difference classement moyen 3 ans
0,2330874,6.0,8.0,-2.0,17500000.0,2.206897,0.791587,0.618421,0.447368,0.171053,...,0.447368,0.171053,1.0,1.0,6.473684,12.500000,-6.026316,6.473684,12.500000,-6.026316
1,2330880,16.0,10.0,6.0,-500000.0,0.928058,-0.074662,0.394737,0.350000,0.044737,...,0.350000,0.044737,0.5,0.5,16.710526,20.000000,-3.289474,16.710526,20.000000,-3.289474
2,2330916,18.0,2.0,16.0,-18200000.0,0.257143,-1.358123,0.473684,0.605263,-0.131579,...,0.605263,-0.131579,0.0,0.0,9.052632,8.236842,0.815789,9.052632,8.236842,0.815789


0    0
1   -1
2   -1
Name: results, dtype: int64

In [41]:
X_train, X_temp, Y_train, Y_temp = train_test_split(X, Y, test_size=0.3, random_state=42)

X_validation, X_test, Y_validation, Y_test = train_test_split(X_temp, Y_temp, test_size=0.5, random_state=42)

In [42]:
#Modèle 1 de référence

y_1_pred_validation = pd.Series([1]*len(X_validation))
y_1_pred_test = pd.Series([1]*len(X_test))

modele.affichage_complet_score(Y_validation,y_1_pred_validation)
modele.affichage_complet_score(Y_test,y_1_pred_test)


Accuracy : 0.43790849673202614
Precision : 0.14596949891067537
Recall : 0.3333333333333333
F1 Score : 0.20303030303030303
Matrice de confusion :
 [[  0   0 195]
 [  0   0 149]
 [  0   0 268]]

Accuracy : 0.46568627450980393
Precision : 0.15522875816993464
Recall : 0.3333333333333333
F1 Score : 0.21181716833890749
Matrice de confusion :
 [[  0   0 169]
 [  0   0 158]
 [  0   0 285]]


c:\Users\anton\Downloads\A3\analyse données\Winunmax\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\anton\Downloads\A3\analyse données\Winunmax\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [44]:
#Modèle 1 de référence

y_2_pred_validation = modele.prediction_modele_simple(X_validation["difference classement moyen 1 ans"])
y_2_pred_test = modele.prediction_modele_simple(X_test["difference classement moyen 1 ans"])

modele.affichage_complet_score(Y_validation,y_2_pred_validation)
modele.affichage_complet_score(Y_test,y_2_pred_test)


Accuracy : 0.44281045751633985
Precision : 0.41906998006744817
Recall : 0.42317461051308586
F1 Score : 0.4184262700652335
Matrice de confusion :
 [[106  45  44]
 [ 51  37  61]
 [ 83  57 128]]

Accuracy : 0.43790849673202614
Precision : 0.3956950535571
Recall : 0.4114758471341262
F1 Score : 0.39606589542413234
Matrice de confusion :
 [[ 94  31  44]
 [ 75  24  59]
 [ 76  59 150]]
