In [236]:
import pandas as pd
from sklearn.model_selection import train_test_split
from IPython.display import display
import numpy as np
from sklearn.feature_selection import mutual_info_classif


%load_ext autoreload
%autoreload 2
import importlib
import sys
sys.path.append("../src/")
import modele
importlib.reload(modele)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


<module 'modele' from 'c:\\Users\\anton\\Downloads\\A3\\analyse données\\Winunmax\\notebooks\\../src\\modele.py'>

In [237]:
df = pd.read_csv("../data/preparee/dataframe_traite.csv")
#Je laisse game_id pour le moment pour des vérifications
X = df.drop(columns=["game_id","home_club_name","away_club_name","date","season","home_club_id","away_club_id","results"]) 
Y = df["results"]
display(X.head(3))
display("classes déséquilibrée ",Y.value_counts())

,home_club_position,away_club_position,difference classement,Difference value home et away,Ratio value home par away,LOG Ratio value home par away,winrate_home 1 ans,winrate_away 1 ans,difference winrate home-away 1 ans,winrate_home 3 ans,...,winrate_confrontation_home 3 ans,pos_moy_home_1_ans,pos_moy_away_1_ans,difference classement moyen home-away 1 ans,pos_moy_home_3_ans,pos_moy_away_3_ans,difference classement moyen home-away 3 ans,evolution classement home 3 et 1 ans,evolution classement away 3 et 1 ans,evolution difference classement entre équipes entre 3 et 1 ans
0,6.0,8.0,-2.0,17500000.0,2.206897,0.791587,0.618421,0.447368,0.171053,0.618421,...,1.0,6.473684,12.500000,-6.026316,6.473684,12.500000,-6.026316,0.0,0.0,0.0
1,16.0,10.0,6.0,-500000.0,0.928058,-0.074662,0.394737,0.350000,0.044737,0.394737,...,0.5,16.710526,20.000000,-3.289474,16.710526,20.000000,-3.289474,0.0,0.0,0.0
2,18.0,2.0,16.0,-18200000.0,0.257143,-1.358123,0.473684,0.605263,-0.131579,0.473684,...,0.0,9.052632,8.236842,0.815789,9.052632,8.236842,0.815789,0.0,0.0,0.0


'classes déséquilibrée '

results
 1    1802
-1    1203
 0    1073
Name: count, dtype: int64

In [238]:
X_sans_classement = X.drop(columns=["difference classement","home_club_position","away_club_position"])
Y_sans_classement = Y.drop(columns=["difference classement","home_club_position","away_club_position"])
mi = mutual_info_classif(X_sans_classement, Y_sans_classement, random_state=42)
mi_series = pd.Series(mi, index=X_sans_classement.columns).sort_values(ascending=False)
print(mi_series)

difference winrate home-away 3 ans                                0.052798
pos_moy_home_3_ans                                                0.050484
difference winrate home-away 1 ans                                0.047273
Difference value home et away                                     0.044165
pos_moy_home_1_ans                                                0.041617
LOG Ratio value home par away                                     0.039815
evolution classement away 3 et 1 ans                              0.037630
winrate_away 1 ans                                                0.037251
difference classement moyen home-away 3 ans                       0.036471
Ratio value home par away                                         0.036359
winrate_home 3 ans                                                0.035176
pos_moy_away_1_ans                                                0.032840
winrate_away 3 ans                                                0.032475
evolution classement home

In [239]:
#Modèle 1 de référence (NAIF)

y_1_pred = pd.Series([1]*len(X))

modele.affichage_complet_score(Y,y_1_pred)


Accuracy : 0.441883276115743
Precision : 0.14729442537191434
Recall : 0.3333333333333333
F1 Score : 0.20430839002267573
Matrice de confusion :
 [[   0    0 1203]
 [   0    0 1073]
 [   0    0 1802]]


c:\Users\anton\Downloads\A3\analyse données\Winunmax\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [244]:
#Modèle 2 de référence

y_2_pred = modele.prediction_modele_simple_diff_winrate(X["difference winrate home-away 3 ans"])

modele.affichage_complet_score(Y,y_2_pred)


Accuracy : 0.4386954389406572
Precision : 0.43159809382608416
Recall : 0.43105726424096275
F1 Score : 0.42737251618637
Matrice de confusion :
 [[615 337 251]
 [382 346 345]
 [425 549 828]]


In [241]:
df_sans_2012 = pd.read_csv("../data/preparee/dataframe_traite_sans_2012.csv")

X_sans_2012 = df_sans_2012.drop(columns=["game_id","home_club_name","away_club_name","date","season","home_club_id","away_club_id","results"]) 
Y_sans_2012 = df_sans_2012["results"]

#X_train_sans_2012, X_temp_sans_2012, Y_train_sans_2012, Y_temp_sans_2012 = train_test_split(X_sans_2012, Y_sans_2012, test_size=0.3, random_state=42)
#X_validation_sans_2012, X_test_sans_2012, Y_validation_sans_2012, Y_test_sans_2012 = train_test_split(X_temp_sans_2012, Y_temp_sans_2012, test_size=0.5, random_state=42)

In [242]:
X_sans_classement_sans_2012 = X_sans_2012.drop(columns=["difference classement","home_club_position","away_club_position"])
Y_sans_classement_sans_2012 = Y_sans_2012.drop(columns=["difference classement","home_club_position","away_club_position"])
mi_sans_2012 = mutual_info_classif(X_sans_classement_sans_2012, Y_sans_classement_sans_2012, random_state=42)
mi_series_sans_2012 = pd.Series(mi_sans_2012, index=X_sans_classement_sans_2012.columns).sort_values(ascending=False)
print(mi_series_sans_2012)

difference winrate home-away 1 ans                                0.066665
pos_moy_home_1_ans                                                0.062994
pos_moy_home_3_ans                                                0.059478
evolution classement home 3 et 1 ans                              0.055750
difference winrate home-away 3 ans                                0.050046
winrate_home 1 ans                                                0.048233
LOG Ratio value home par away                                     0.045692
Ratio value home par away                                         0.045159
evolution classement away 3 et 1 ans                              0.041441
Difference value home et away                                     0.040502
winrate_home 3 ans                                                0.039376
winrate_away 3 ans                                                0.038506
pos_moy_away_1_ans                                                0.034905
difference classement moy

In [245]:
#Modèle 2 de référence

y_2_pred_sans_2012 = modele.prediction_modele_simple_diff_winrate(X_sans_2012["difference winrate home-away 3 ans"])

modele.affichage_complet_score(Y_sans_2012,y_2_pred_sans_2012)

print("\nAccuracy meilleure de 1.7 points et F1 score meilleur de 0.3 points, on peut supposer que c’est meilleur mais à vérifier car possiblement du bruit")


Accuracy : 0.4545700378583018
Precision : 0.43109761621293047
Recall : 0.4375227239319441
F1 Score : 0.43045665356479884
Matrice de confusion :
 [[615 235 251]
 [382 238 345]
 [425 379 828]]

Accuracy meilleure de 1.7 points et F1 score meilleur de 0.3 points, on peut supposer que c’est meilleur mais à vérifier car possiblement du bruit
